### ISSUE TITLE
Batched file downloads

### ISSUE THREAD

**Issue by lferran** [guillotinaweb/guillotina_batch#9]
I'm having problems trying to download several files into a single `@batch` call

I couldn't really reproduce the same error that I'm getting on my guillotina installation yet, but the traceback that I get is:

```
Error on execution of view 6b92591c3d954c2eb98dde045d6b4da2
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/guillotina/traversal.py", line 231, in handler
    view_result = await self.view()
  File "/guillotina_batch/guillotina_batch/api.py", line 214, in __call__
    results.append(await self.handle(message))
  File "/guillotina_batch/guillotina_batch/api.py", line 123, in handle
    result = await self._handle(request, message)
  File "/guillotina_batch/guillotina_batch/api.py", line 200, in _handle
    'body': view_result.body.read().decode('utf-8'),
AttributeError: 'StreamResponse' object has no attribute 'body'
```

Unclear to me how we should read the body/contents from the `StreamResponse` to later place them in the `@batch` response.

**Comment by vangheem** [comment]
Downloading is a streamed response--you won't be able to download multiple in a batch unless you somehow manage the output of each batched response stream individually. But why would you want to do that?

How do you want to combine these files for the output?

JSON doesn't speak binary so you'd also need to convert these file downloads to base64. The response JSON could be massive.

I would advise against this.

**Comment by lferran** [comment]
totally right :smile_cat:.. thanks for the feedback
